project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Archive"
    foreground: "#181622"


format:
  html:
    theme: custom.scss
    css: style.css
    header-includes: |
      <link href='https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600&family=Poppins:wght@100;200;300;400;500;600;700;800&display=swap' rel='stylesheet'>
